Add new setup-poetry action and fix nightly-release (#212)
## Problem
`nightly-release` workflow is still failing after the previous "fix":
https://github.com/pinecone-io/pinecone-python-client/pull/208.

This time it's due to `make package` failing on `poetry build`, because
`poetry` wasn't setup properly in the workflow.

https://github.com/pinecone-io/pinecone-python-client/actions/runs/6399744230/job/17372332268

> Run make package
poetry build
make: poetry: No such file or directory
make: *** [Makefile:22: package] Error
[12](https://github.com/pinecone-io/pinecone-python-client/actions/runs/6399744230/job/17372332268#step:9:13)7
Error: Process completed with exit code 2.

While fixing this I noticed we're also not installing Poetry in the
`publish-to-pypi` workflow, so calling `poetry version` and `make`
commands there would fail. We need to make sure we're installing Poetry
properly before using `make` in our workflows, as they call Poetry under
the hood.

## Solution
- Add a new `setup-poetry` action that encapsulates the install +
dependencies bits. I noticed we were doing this explicitly in several
workflows and thought it called for an action.
- Fix `nightly-release` worfklow: call the new action before calling
`make package`.
- Fix `release-to-pypi` worfklow: call the new action before calling
`poetry version`, and `make` commands for publishing.
- Clean up / use the action in `testing` worfklow.

## Type of Change
- [X] Infrastructure change (CI configs, etc)

## Test Plan
Validate PR workflows pass as expected. Merge and check
`nightly-release` to make sure we're in good shape.