Use `@require_kwargs` decorator on new methods (#480)
## Problem

Python methods can be invoked with both positional and keyword
arguments, however the keyword argument form has a number of benefits
such as:
- The keyword argument label acts as a minor form of documentation
- Keyword arguments can be passed in any order, whereas positional
arguments must be passed in a specific fixed order. This order
flexibility works well when there are large numbers of optional
parameters
- If a function takes several parameters of the same type (e.g. str),
it's very easy to accidentally pass them in the wrong order since you
won't run into a type-related error letting you know you've done
something wrong. Keyword args don't have this problem.
- With positional arguments you must pass arguments with no default
value before those that have a default value; this means you can't add a
new default value without having to shuffle your argument order which
creates a breaking change out of what should be a benign UX improvement.
Keyword args do not have this limitation.

## Solution

I recently implemented a decorator called @kwargs_required that will
give an informative error if caller attempts to pass values as
positional arguments.

This PR is a follow-up to apply that decorator to all methods that are
newly added in the upcoming release. Adding this decorator would be a
breaking change for existing methods, so for now I will hold off on
doing that.

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

## Testing

```python
>>> pc.db.index.describe('foofoo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jhamon/workspace/pinecone-python-client/pinecone/utils/require_kwargs.py", line 10, in wrapper
    raise TypeError(
TypeError: describe() requires keyword arguments. Please use describe(name=value)
>>> pc.db.index.describe(name='foofoo')
{
    "name": "foofoo",
    "metric": "cosine",
    "host": "foofoo-dojoi3u.svc.aped-4627-b74a.pinecone.io",
    "spec": {
        "serverless": {
            "cloud": "aws",
            "region": "us-east-1"
        }
    },
    "status": {
        "ready": true,
        "state": "Ready"
    },
    "vector_type": "dense",
    "dimension": 2,
    "deletion_protection": "disabled",
    "tags": null
}
```